Improve the MATLAB detection.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10,11 +10,42 @@ if [ -e Makefile.inc ]; then
 fi
 
 # Try to find MATLAB
-MATLAB_CMD=$(command -v matlab)
-if [ "$?" -ne "0" ]; then
-  echo "Cannot find MATLAB, please specify its path by using "
-  echo "./configure /path/to/MATLAB/bin/matlab"
-  exit 1
+MATLAB_CMD="$1"
+if [ "$MATLAB_CMD" = "" ]; then
+  MATLAB_CMD=$(command -v matlab)
+fi
+
+if [ "$MATLAB_CMD" = "" ]; then
+  # Try to find Matlab guessing its location and using locate, first
+  for possible_path in $(locate --regex bin/matlab\$); do
+    if [ -x "$possible_path" ]; then
+      grep "Mathworks" "$possible_path" > /dev/null
+      if [ $? -eq 0 ]; then
+        MATLAB_CMD="$possible_path"
+        break
+      fi
+    fi
+  done
+
+  # Try a wild guess looking for bin/matlab in user home
+  if [ "$HOME" != "" ]; then
+    echo "Matlab not found, looking for it in your home folder (it might take a while)"
+    for possible_path in $(find "$HOME" -name matlab -type f 2> /dev/null); do
+      if [ -x "$possible_path" ]; then
+        grep "MathWorks" "$possible_path" > /dev/null
+        if [ "$?" -eq "0" ]; then
+          MATLAB_CMD="$possible_path"
+          break
+        fi
+      fi
+    done
+  fi
+
+  if [ "$MATLAB_CMD" = "" ]; then
+    echo "Cannot find MATLAB, please specify its path by using "
+    echo "./configure /path/to/MATLAB/bin/matlab"
+    exit 1
+  fi
 fi
 
 echo "Selected $MATLAB_CMD as the default Matlab environment"
